/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.NhanVienNhapLieu;

import UI.NhanVienNhapLieu.GiaoDienQLTaiLieu;
import UI.NhanVienNhapLieu.GiaoDienThongKeTaiLieu;
import UI.NhanVienNhapLieu.GiaoDienQLDocGia;
import UI.NhanVienNhapLieu.GiaoDienQLTacGia;
import Helper.DatabaseManager;
import Helper.MayIn;
import UI.GiaoDienDangNhap;
import java.awt.Cursor;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author tinhlam
 */
public class GiaoDienNhanVienNhapLieu extends javax.swing.JFrame {

    GiaoDienDangNhap parent;
    
    /**
     * Creates new form GiaoDienNhanVienNhapLieu
     */
    public GiaoDienNhanVienNhapLieu(GiaoDienDangNhap parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        changeAccBtn = new javax.swing.JButton();
        topLb = new javax.swing.JLabel();
        botPanel = new javax.swing.JPanel();
        botLb = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        tacGiaPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        saoLuuPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        thongKePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        docGiaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        taiLieuPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        khoiPhucPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        topPanel.setBackground(new java.awt.Color(51, 102, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        exitBtn.setBackground(new java.awt.Color(255, 0, 0));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Thoát");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        changeAccBtn.setBackground(new java.awt.Color(102, 102, 102));
        changeAccBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeAccBtn.setText("Đổi tài khoản");
        changeAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAccBtnActionPerformed(evt);
            }
        });

        topLb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        topLb.setForeground(new java.awt.Color(255, 255, 255));
        topLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLb.setText("Giao Diện Nhân Viên Nhập Liệu");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeAccBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        botPanel.setBackground(new java.awt.Color(51, 102, 255));
        botPanel.setMinimumSize(new java.awt.Dimension(100, 0));
        botPanel.setPreferredSize(new java.awt.Dimension(1000, 30));

        botLb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        botLb.setForeground(new java.awt.Color(255, 255, 255));
        botLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botLb.setText("Copyright © 2023");
        botLb.setPreferredSize(new java.awt.Dimension(1000, 30));

        javax.swing.GroupLayout botPanelLayout = new javax.swing.GroupLayout(botPanel);
        botPanel.setLayout(botPanelLayout);
        botPanelLayout.setHorizontalGroup(
            botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(botLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botPanelLayout.setVerticalGroup(
            botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botPanelLayout.createSequentialGroup()
                .addComponent(botLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(botPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setPreferredSize(new java.awt.Dimension(1000, 670));

        tacGiaPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        tacGiaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseExited(evt);
            }
        });
        tacGiaPanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(51, 102, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tác Giả");
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 50));
        tacGiaPanel.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jLabel9.setBackground(new java.awt.Color(51, 102, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/writer.png"))); // NOI18N
        jLabel9.setOpaque(true);
        tacGiaPanel.add(jLabel9, java.awt.BorderLayout.CENTER);

        saoLuuPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        saoLuuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saoLuuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseExited(evt);
            }
        });
        saoLuuPanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(51, 102, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sao Lưu CSDL");
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 50));
        saoLuuPanel.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        jLabel6.setBackground(new java.awt.Color(51, 102, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backup.png"))); // NOI18N
        jLabel6.setOpaque(true);
        saoLuuPanel.add(jLabel6, java.awt.BorderLayout.CENTER);

        thongKePanel.setPreferredSize(new java.awt.Dimension(200, 200));
        thongKePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseExited(evt);
            }
        });
        thongKePanel.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(51, 102, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thống Kê");
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 50));
        thongKePanel.add(jLabel5, java.awt.BorderLayout.PAGE_END);

        jLabel10.setBackground(new java.awt.Color(51, 102, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analytics.png"))); // NOI18N
        jLabel10.setOpaque(true);
        thongKePanel.add(jLabel10, java.awt.BorderLayout.CENTER);

        docGiaPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        docGiaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docGiaPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseExited(evt);
            }
        });
        docGiaPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Độc Giả");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 50));
        docGiaPanel.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jLabel8.setBackground(new java.awt.Color(51, 102, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reading.png"))); // NOI18N
        jLabel8.setOpaque(true);
        docGiaPanel.add(jLabel8, java.awt.BorderLayout.CENTER);

        taiLieuPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        taiLieuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hienThiFormQLTaiLieu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseExited(evt);
            }
        });
        taiLieuPanel.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(51, 102, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tài Liệu");
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(200, 50));
        taiLieuPanel.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jLabel12.setBackground(new java.awt.Color(51, 102, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        jLabel12.setOpaque(true);
        taiLieuPanel.add(jLabel12, java.awt.BorderLayout.CENTER);

        khoiPhucPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        khoiPhucPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khoiPhucPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tacGiaPanelMouseExited(evt);
            }
        });
        khoiPhucPanel.setLayout(new java.awt.BorderLayout());

        jLabel13.setBackground(new java.awt.Color(51, 102, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Khôi Phục CSDL");
        jLabel13.setOpaque(true);
        jLabel13.setPreferredSize(new java.awt.Dimension(200, 50));
        khoiPhucPanel.add(jLabel13, java.awt.BorderLayout.PAGE_END);

        jLabel14.setBackground(new java.awt.Color(51, 102, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restore.png"))); // NOI18N
        jLabel14.setOpaque(true);
        khoiPhucPanel.add(jLabel14, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(saoLuuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(khoiPhucPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(taiLieuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(docGiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(tacGiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(thongKePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tacGiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docGiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thongKePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiLieuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saoLuuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khoiPhucPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tacGiaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tacGiaPanelMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_tacGiaPanelMouseEntered

    private void tacGiaPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tacGiaPanelMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_tacGiaPanelMouseExited

    private void hienThiFormQLTaiLieu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hienThiFormQLTaiLieu
        GiaoDienQLTaiLieu form = new GiaoDienQLTaiLieu(this);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hienThiFormQLTaiLieu

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void changeAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAccBtnActionPerformed
        parent.resetComponents();
        parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_changeAccBtnActionPerformed

    private void docGiaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docGiaPanelMouseClicked
        GiaoDienQLDocGia form = new GiaoDienQLDocGia(this);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_docGiaPanelMouseClicked

    private void tacGiaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tacGiaPanelMouseClicked
        GiaoDienQLTacGia form = new GiaoDienQLTacGia(this);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tacGiaPanelMouseClicked

    private void thongKePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKePanelMouseClicked
        GiaoDienThongKeTaiLieu form = new GiaoDienThongKeTaiLieu(this);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_thongKePanelMouseClicked

    private void saoLuuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saoLuuPanelMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(""));
        chooser.setDialogTitle("Chọn đường dẫn lưu file csdl");
        FileFilter filter = new FileNameExtensionFilter("SQL File", "sql");
        chooser.setFileFilter(filter);
        int op = chooser.showSaveDialog(this);
        String path = "";
        if (op == JFileChooser.APPROVE_OPTION) {
            path = chooser.getSelectedFile().toString();
            DatabaseManager.saoLuuDuLieu(path);
            JOptionPane.showMessageDialog(this, "Sao lưu thành công");
        }
    }//GEN-LAST:event_saoLuuPanelMouseClicked

    private void khoiPhucPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoiPhucPanelMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(""));
        chooser.setDialogTitle("Chọn file dữ liệu");
        FileFilter filter = new FileNameExtensionFilter("SQL File", "sql");
        chooser.setFileFilter(filter);
        int op = chooser.showOpenDialog(this);
        String path = "";
        if (op == JFileChooser.APPROVE_OPTION) {
            path = chooser.getSelectedFile().toString();
            DatabaseManager.khoiPhucDuLieu(path);
            JOptionPane.showMessageDialog(this, "Khôi phục thành công");
        }
    }//GEN-LAST:event_khoiPhucPanelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botLb;
    private javax.swing.JPanel botPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton changeAccBtn;
    private javax.swing.JPanel docGiaPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel khoiPhucPanel;
    private javax.swing.JPanel saoLuuPanel;
    private javax.swing.JPanel tacGiaPanel;
    private javax.swing.JPanel taiLieuPanel;
    private javax.swing.JPanel thongKePanel;
    private javax.swing.JLabel topLb;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
