/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.DocGia;

import Entity.DatTruoc;
import Entity.DongDatTruoc;
import Entity.Sach;
import Entity.TaiLieu;
import Entity.TapChi;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tinhlam
 */
public class GiaoDienDocGia extends javax.swing.JFrame {

    ArrayList<TaiLieu> ds;
    DefaultTableCellRenderer headerRenderer;
    GiaoDienTaiLieuDatTruoc tldt;

    /**
     * Creates new form GiaoDienDocGia
     */
    public GiaoDienDocGia() {
        initComponents();
        setup();
    }

    private void setup() {
        final Color BLUE_COLOR = new Color(51, 102, 255, 255);
        final Color WHITE_COLOR = new Color(255, 255, 255, 255);

        headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(BLUE_COLOR);
        headerRenderer.setForeground(WHITE_COLOR);
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(150);
        }
        jTable1.setGridColor(BLUE_COLOR);
        jTable1.setForeground(BLUE_COLOR);
        jTable1.setShowGrid(true);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        ds = new Sach().layDanhSach();
        System.out.println(ds.size());
        tldt = new GiaoDienTaiLieuDatTruoc();
        renderTable();
    }

    private void renderTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(Sach.getProperties());
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(150);
        }
        for (TaiLieu tl : ds) {
            if (tl instanceof Sach) {
                Sach sach = (Sach) tl;
                model.addRow(sach.getValues());
            } else {
                TapChi tapChi = (TapChi) tl;
                model.addRow(tapChi.getValues());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        topLb = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        centerTopPanel = new javax.swing.JPanel();
        tenTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        timTheoTenBtn = new javax.swing.JButton();
        sachBtn = new javax.swing.JRadioButton();
        tapChiBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        TLORLVTf = new javax.swing.JTextField();
        timTheoTLORLVBtn = new javax.swing.JButton();
        xemBtn = new javax.swing.JButton();
        themBtn = new javax.swing.JButton();
        quanLyBtn = new javax.swing.JButton();
        centerCenterPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(51, 102, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        topLb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        topLb.setForeground(new java.awt.Color(255, 255, 255));
        topLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLb.setText("Danh Sách Tài Liệu");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        mainPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        centerPanel.setLayout(new java.awt.BorderLayout());

        centerTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerTopPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Tên");

        timTheoTenBtn.setBackground(new java.awt.Color(51, 102, 255));
        timTheoTenBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timTheoTenBtn.setForeground(new java.awt.Color(255, 255, 255));
        timTheoTenBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        timTheoTenBtn.setText("Tìm");
        timTheoTenBtn.setBorder(null);
        timTheoTenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timTheoTenBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(sachBtn);
        sachBtn.setForeground(new java.awt.Color(51, 102, 255));
        sachBtn.setSelected(true);
        sachBtn.setText("Sách");
        sachBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sachBtnItemStateChanged(evt);
            }
        });

        buttonGroup1.add(tapChiBtn);
        tapChiBtn.setForeground(new java.awt.Color(51, 102, 255));
        tapChiBtn.setText("Tạp Chí");
        tapChiBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tapChiBtnsachBtnItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Thể Loại");

        timTheoTLORLVBtn.setBackground(new java.awt.Color(51, 102, 255));
        timTheoTLORLVBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timTheoTLORLVBtn.setForeground(new java.awt.Color(255, 255, 255));
        timTheoTLORLVBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        timTheoTLORLVBtn.setText("Tìm");
        timTheoTLORLVBtn.setBorder(null);
        timTheoTLORLVBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timTheoTLORLVBtnActionPerformed(evt);
            }
        });

        xemBtn.setBackground(new java.awt.Color(51, 102, 255));
        xemBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xemBtn.setForeground(new java.awt.Color(255, 255, 255));
        xemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/read.png"))); // NOI18N
        xemBtn.setText("Xem");
        xemBtn.setBorder(null);
        xemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemBtnActionPerformed(evt);
            }
        });

        themBtn.setBackground(new java.awt.Color(51, 102, 255));
        themBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        themBtn.setForeground(new java.awt.Color(255, 255, 255));
        themBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_to_list.png"))); // NOI18N
        themBtn.setText("Thêm");
        themBtn.setBorder(null);
        themBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtnActionPerformed(evt);
            }
        });

        quanLyBtn.setBackground(new java.awt.Color(51, 102, 255));
        quanLyBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quanLyBtn.setForeground(new java.awt.Color(255, 255, 255));
        quanLyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/books.png"))); // NOI18N
        quanLyBtn.setText("Quản lý ");
        quanLyBtn.setBorder(null);
        quanLyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centerTopPanelLayout = new javax.swing.GroupLayout(centerTopPanel);
        centerTopPanel.setLayout(centerTopPanelLayout);
        centerTopPanelLayout.setHorizontalGroup(
            centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sachBtn)
                    .addComponent(tapChiBtn))
                .addGap(18, 18, 18)
                .addComponent(themBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(quanLyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenTf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timTheoTenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TLORLVTf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timTheoTLORLVBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(xemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        centerTopPanelLayout.setVerticalGroup(
            centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(centerTopPanelLayout.createSequentialGroup()
                        .addComponent(sachBtn)
                        .addGap(18, 18, 18)
                        .addComponent(tapChiBtn))
                    .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(themBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timTheoTLORLVBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timTheoTenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tenTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(TLORLVTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(quanLyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        centerPanel.add(centerTopPanel, java.awt.BorderLayout.PAGE_START);

        centerCenterPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerCenterPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        centerCenterPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        centerCenterPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centerPanel.add(centerCenterPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void timTheoTenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timTheoTenBtnActionPerformed
        if (tenTf.getText().equals("")) {
            if (sachBtn.isSelected()) {
                ds = new Sach().layDanhSach();
            } else {
                ds = new TapChi().layDanhSach();
            }
            renderTable();
            return;
        }
        if (sachBtn.isSelected()) {
            ds = new Sach().timKiemTheoTen(tenTf.getText());
        } else {
            ds = new TapChi().timKiemTheoTen(tenTf.getText());
        }
        renderTable();
    }//GEN-LAST:event_timTheoTenBtnActionPerformed

    private void sachBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sachBtnItemStateChanged
        if (sachBtn.isSelected()) {
            ds = new Sach().layDanhSach();
            jLabel4.setText("Thể loại");
        } else {
            ds = new TapChi().layDanhSach();
            jLabel4.setText("Lĩnh vực");
        }
        renderTable();
    }//GEN-LAST:event_sachBtnItemStateChanged

    private void tapChiBtnsachBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tapChiBtnsachBtnItemStateChanged
        if (sachBtn.isSelected()) {
            ds = new Sach().layDanhSach();
            jLabel4.setText("Thể loại");
        } else {
            ds = new TapChi().layDanhSach();
            jLabel4.setText("Lĩnh vực");
        }
        renderTable();
    }//GEN-LAST:event_tapChiBtnsachBtnItemStateChanged

    private void timTheoTLORLVBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timTheoTLORLVBtnActionPerformed
        if (TLORLVTf.getText().equals("")) {
            if (sachBtn.isSelected()) {
                ds = new Sach().layDanhSach();
            } else {
                ds = new TapChi().layDanhSach();
            }
            renderTable();
            return;
        }
        if (sachBtn.isSelected()) {
            ds = new Sach().timKiemTheoTheLoai(TLORLVTf.getText());
        } else {
            ds = new TapChi().timKiemTheoLinhVuc(TLORLVTf.getText());
        }
        renderTable();
    }//GEN-LAST:event_timTheoTLORLVBtnActionPerformed


    private void themBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtnActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Dữ liệu chọn không hợp lệ");
            return;
        }
        TaiLieu taiLieu = ds.get(row);
        tldt.them(taiLieu);
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_themBtnActionPerformed

    private void quanLyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyBtnActionPerformed
        tldt.openFrame();
    }//GEN-LAST:event_quanLyBtnActionPerformed

    private void xemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemBtnActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Dữ liệu chọn không hợp lệ");
            return;
        }
        if (ds.get(row).laAnPhamGiay()) {
            JOptionPane.showMessageDialog(this, "Không phải ấn phẩm điện tử");
            return;
        }
        GiaoDienXemTaiLieu form = new GiaoDienXemTaiLieu(ds.get(row));
        form.setVisible(true);
    }//GEN-LAST:event_xemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienDocGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TLORLVTf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel centerCenterPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerTopPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton quanLyBtn;
    private javax.swing.JRadioButton sachBtn;
    private javax.swing.JRadioButton tapChiBtn;
    private javax.swing.JTextField tenTf;
    private javax.swing.JButton themBtn;
    private javax.swing.JButton timTheoTLORLVBtn;
    private javax.swing.JButton timTheoTenBtn;
    private javax.swing.JLabel topLb;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton xemBtn;
    // End of variables declaration//GEN-END:variables
}
