/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ThuThu;

import Entity.DatTruoc;
import Entity.DocGia;
import Entity.DongMuon;
import Entity.Muon;
import Helper.Email;
import java.awt.Color;
import java.awt.Dimension;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tinhlam
 */
public class GiaoDienGuiEmail extends javax.swing.JFrame {

    JFrame parent;
    ArrayList<Muon> ds;

    /**
     * Creates new form GiaoDienGuiEmail
     */
    public GiaoDienGuiEmail(JFrame parent) {
        this.parent = parent;
        initComponents();
        setup();
        loadDefaultList();
        renderTable();
    }

    private void setup() {
        final Color BLUE_COLOR = new Color(51, 102, 255, 255);
        final Color WHITE_COLOR = new Color(255, 255, 255, 255);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(BLUE_COLOR);
        headerRenderer.setForeground(WHITE_COLOR);
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        jTable1.setGridColor(BLUE_COLOR);
        jTable1.setForeground(BLUE_COLOR);
        jTable1.setShowGrid(true);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    public void loadDefaultList() {
        ds = Muon.layDanhSachTheoSoNgayMuonConLai(14);
    }

    private void renderTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Muon m : ds) {
            String sh = String.valueOf(m.getDocGia().getSoHieu());
            String tgtdk = m.getThoiGianTraDuKien().format(DateTimeFormatter.ofPattern("dd-MM-yyyy hh:mm:ss"));
            model.addRow(new Object[]{false, sh, tgtdk});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        topLb = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        centerTopPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        layDanhSachBtn = new javax.swing.JButton();
        guiBtn = new javax.swing.JButton();
        ngayMuonConLaiTf = new javax.swing.JTextField();
        centerCenterPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(51, 102, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        topLb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        topLb.setForeground(new java.awt.Color(255, 255, 255));
        topLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLb.setText("Gửi Thông Báo");

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(51, 102, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go_back.png"))); // NOI18N
        backBtn.setText("Trở Về");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(176, 176, 176))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        centerPanel.setLayout(new java.awt.BorderLayout());

        centerTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerTopPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Số ngày mượn còn lại");

        layDanhSachBtn.setBackground(new java.awt.Color(51, 102, 255));
        layDanhSachBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        layDanhSachBtn.setForeground(new java.awt.Color(255, 255, 255));
        layDanhSachBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filter.png"))); // NOI18N
        layDanhSachBtn.setText("Lấy danh sách");
        layDanhSachBtn.setBorder(null);
        layDanhSachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layDanhSachBtnActionPerformed(evt);
            }
        });

        guiBtn.setBackground(new java.awt.Color(51, 102, 255));
        guiBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guiBtn.setForeground(new java.awt.Color(255, 255, 255));
        guiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email_30px.png"))); // NOI18N
        guiBtn.setText("Gửi");
        guiBtn.setBorder(null);
        guiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centerTopPanelLayout = new javax.swing.GroupLayout(centerTopPanel);
        centerTopPanel.setLayout(centerTopPanelLayout);
        centerTopPanelLayout.setHorizontalGroup(
            centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ngayMuonConLaiTf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layDanhSachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                .addComponent(guiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        centerTopPanelLayout.setVerticalGroup(
            centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(layDanhSachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ngayMuonConLaiTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        centerPanel.add(centerTopPanel, java.awt.BorderLayout.PAGE_START);

        centerCenterPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerCenterPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        centerCenterPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chọn", "Số hiệu độc giả", "Thời gian trả dự kiến"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        centerCenterPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centerPanel.add(centerCenterPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void layDanhSachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layDanhSachBtnActionPerformed
        if (ngayMuonConLaiTf.getText().equals("")) {
            loadDefaultList();
        } else {
            try {
                int ngay = Integer.valueOf(ngayMuonConLaiTf.getText());
                ds = Muon.layDanhSachTheoSoNgayMuonConLai(ngay);
            } catch (NumberFormatException e) {
                ds = new ArrayList<>();
            }
        }
        renderTable();
    }//GEN-LAST:event_layDanhSachBtnActionPerformed

    private void guiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiBtnActionPerformed
        JTextField tieuDeTf = new JTextField();
        JTextArea noiDungTa = new JTextArea();
        noiDungTa.setPreferredSize(new Dimension(300, 300));
        Object[] coms = {
            "Tiêu đề", tieuDeTf,
            "Nội dung", noiDungTa
        };
        JOptionPane pane = new JOptionPane();
        int op = pane.showConfirmDialog(this, coms, "Thông tin email", JOptionPane.OK_CANCEL_OPTION);
        if (op == JOptionPane.OK_OPTION) {
            Email email = new Email();
            email.setTieuDe(tieuDeTf.getText());
            email.setNoiDung(noiDungTa.getText());
            ArrayList<DocGia> dsdg = new ArrayList<>();
            for (int i = 0; i < jTable1.getModel().getRowCount(); i++) {
                if ((boolean) jTable1.getModel().getValueAt(i, 0) == true) {
                    dsdg.add(ds.get(i).getDocGia());
                }
            }
            email.setDanhSachDocGia(dsdg);
            email.guiEmail();
            JOptionPane.showMessageDialog(this, "Gửi email thành công");
        }
    }//GEN-LAST:event_guiBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel centerCenterPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerTopPanel;
    private javax.swing.JButton guiBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton layDanhSachBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField ngayMuonConLaiTf;
    private javax.swing.JLabel topLb;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
