/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ThuThu;

import Entity.DatTruoc;
import Entity.DongDatTruoc;
import Helper.MayIn;
import Helper.ThongKe;
import Helper.ThongKeGiaoDich;
import Helper.ThongKeTaiLieu;
import java.awt.Color;
import java.io.File;
import java.lang.reflect.Field;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tinhlam
 */
public class GiaoDienThongKeGiaoDich extends javax.swing.JFrame {

    JFrame parent;
    ThongKe thongKe;
    DefaultTableCellRenderer headerRenderer;

    /**
     * Creates new form GiaoDienThongKe
     *
     * @param parent
     */
    public GiaoDienThongKeGiaoDich(JFrame parent) {
        this.parent = parent;
        initComponents();
        setup();
    }

    private void setup() {
        final Color BLUE_COLOR = new Color(51, 102, 255, 255);
        final Color WHITE_COLOR = new Color(255, 255, 255, 255);

        headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(BLUE_COLOR);
        headerRenderer.setForeground(WHITE_COLOR);
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        jTable1.setGridColor(BLUE_COLOR);
        jTable1.setForeground(BLUE_COLOR);
        jTable1.setShowGrid(true);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    private void renderTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        ThongKeGiaoDich tk = (ThongKeGiaoDich) thongKe;
        model.setColumnIdentifiers(ThongKeGiaoDich.getProperties());
        model.addRow(tk.getValues());
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        topLb = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        centerTopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ngayBatDauDC = new com.toedter.calendar.JDateChooser();
        ngayKetThucDC = new com.toedter.calendar.JDateChooser();
        thongKeBtn = new javax.swing.JButton();
        xuatFileExcelBtn = new javax.swing.JButton();
        centerCenterPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(51, 102, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        topLb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        topLb.setForeground(new java.awt.Color(255, 255, 255));
        topLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLb.setText("Thống Kê Giao Dịch");

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(51, 102, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go_back.png"))); // NOI18N
        backBtn.setText("Trở Về");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(176, 176, 176))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        centerPanel.setLayout(new java.awt.BorderLayout());

        centerTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerTopPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Ngày bắt đầu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Ngày kết thúc");

        ngayBatDauDC.setBackground(new java.awt.Color(51, 102, 255));
        ngayBatDauDC.setDateFormatString("dd-MM-yyyy");
        ngayBatDauDC.setMaxSelectableDate(new java.util.Date(253370743299000L));
        ngayBatDauDC.setPreferredSize(new java.awt.Dimension(150, 28));

        ngayKetThucDC.setBackground(new java.awt.Color(51, 102, 255));
        ngayKetThucDC.setDateFormatString("dd-MM-yyyy");
        ngayKetThucDC.setPreferredSize(new java.awt.Dimension(150, 28));

        thongKeBtn.setBackground(new java.awt.Color(51, 102, 255));
        thongKeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thongKeBtn.setForeground(new java.awt.Color(255, 255, 255));
        thongKeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analystics_30px.png"))); // NOI18N
        thongKeBtn.setText("Thống Kê");
        thongKeBtn.setBorder(null);
        thongKeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongKeBtnActionPerformed(evt);
            }
        });

        xuatFileExcelBtn.setBackground(new java.awt.Color(51, 102, 255));
        xuatFileExcelBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xuatFileExcelBtn.setForeground(new java.awt.Color(255, 255, 255));
        xuatFileExcelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/export_30px.png"))); // NOI18N
        xuatFileExcelBtn.setText("Xuất Excel");
        xuatFileExcelBtn.setBorder(null);
        xuatFileExcelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatFileExcelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centerTopPanelLayout = new javax.swing.GroupLayout(centerTopPanel);
        centerTopPanel.setLayout(centerTopPanelLayout);
        centerTopPanelLayout.setHorizontalGroup(
            centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngayKetThucDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayBatDauDC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thongKeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 484, Short.MAX_VALUE)
                .addComponent(xuatFileExcelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        centerTopPanelLayout.setVerticalGroup(
            centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerTopPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(xuatFileExcelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centerTopPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(centerTopPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(centerTopPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(thongKeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(centerTopPanelLayout.createSequentialGroup()
                                .addComponent(ngayBatDauDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ngayKetThucDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        centerPanel.add(centerTopPanel, java.awt.BorderLayout.PAGE_START);

        centerCenterPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerCenterPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        centerCenterPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        centerCenterPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centerPanel.add(centerCenterPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void thongKeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongKeBtnActionPerformed
        ArrayList<LocalDate> dates = ThongKe.getMinMaxDate("thoiGianMuon", "Muon");
        if (dates == null){
            return;
        }
        LocalDate bd = dates.get(0);
        LocalDate kt = dates.get(1);
        if (ngayBatDauDC.getDate() != null) {
            bd = ngayBatDauDC.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        if (ngayKetThucDC.getDate() != null) {
            kt = ngayKetThucDC.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        thongKe = new ThongKeGiaoDich(bd, kt).layThongKe();
        renderTable();
    }//GEN-LAST:event_thongKeBtnActionPerformed

    private void xuatFileExcelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatFileExcelBtnActionPerformed
        if (thongKe == null) {
            return;
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(""));
        chooser.setDialogTitle("Chọn đường dẫn lưu file excel");
        FileFilter filter = new FileNameExtensionFilter("XLSX File", "xlsx");
        chooser.setFileFilter(filter);
        int op = chooser.showSaveDialog(this);
        String path = "";
        if (op == JFileChooser.APPROVE_OPTION) {
            path = chooser.getSelectedFile().toString();
            MayIn.xuatFileExcel(thongKe, path);
            JOptionPane.showMessageDialog(this, "Xuất file thành công");
        }
    }//GEN-LAST:event_xuatFileExcelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel centerCenterPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerTopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private com.toedter.calendar.JDateChooser ngayBatDauDC;
    private com.toedter.calendar.JDateChooser ngayKetThucDC;
    private javax.swing.JButton thongKeBtn;
    private javax.swing.JLabel topLb;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton xuatFileExcelBtn;
    // End of variables declaration//GEN-END:variables
}
