/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ThuThu;

import Entity.DocGia;
import Entity.DongMuon;
import Entity.Muon;
import Entity.Sach;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;

/**
 *
 * @author tinhlam
 */
public class GiaoDienSuaMuon extends javax.swing.JFrame {

    GiaoDienMuonTra parent;
    Muon muon;
    /**
     * Creates new form GiaoDienSuaMuon
     */
    public GiaoDienSuaMuon(GiaoDienMuonTra parent, Muon muon) {
        this.parent = parent;
        this.muon = muon;
        initComponents();
        setup();
    }
    
    private void setup() {
        DefaultTableModel model = (DefaultTableModel) taiLieuTb.getModel();
        model.setColumnIdentifiers(new Object[]{"Số hiệu tài liệu", "Số lượng"});
        
        final Color BLUE_COLOR = new Color(51, 102, 255, 255);
        final Color WHITE_COLOR = new Color(255, 255, 255, 255);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(BLUE_COLOR);
        headerRenderer.setForeground(WHITE_COLOR);
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < taiLieuTb.getModel().getColumnCount(); i++) {
            taiLieuTb.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        taiLieuTb.setGridColor(BLUE_COLOR);
        taiLieuTb.setForeground(BLUE_COLOR);
        taiLieuTb.setShowGrid(true);
        taiLieuTb.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        LocalDateTime thoiGianMuon = muon.getThoiGianMuon();
        LocalDateTime thoiGianTraDuKien = muon.getThoiGianTraDuKien();
        thoiGianMuonTf.setText(thoiGianMuon.format(DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm:ss")));
        thoiGianTraDuKienTf.setText(thoiGianTraDuKien.format(DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm:ss")));
        soHieuDocGiaTf.setText(String.valueOf(muon.getDocGia().getSoHieu()));
        for (int i = 0; i < muon.getDanhSachDongMuon().size(); i++){
            int soHieuTaiLieu = muon.getDanhSachDongMuon().get(i).getTaiLieu().getSoHieu();
            int soLuong = muon.getDanhSachDongMuon().get(i).getSoLuong();
            model.addRow(new Object[]{soHieuTaiLieu, soLuong});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        soHieuDocGiaTf = new javax.swing.JTextField();
        huyBtn = new javax.swing.JButton();
        suaBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        themTaiLieuBtn = new javax.swing.JButton();
        xoaTaiLieuBtn = new javax.swing.JButton();
        soHieuTaiLieuTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        soLuongTf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taiLieuTb = new javax.swing.JTable();
        thoiGianMuonTf = new javax.swing.JTextField();
        thoiGianTraDuKienTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(723, 450));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Số hiệu độc giả");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 255));
        jLabel11.setText("Thời gian mượn");

        soHieuDocGiaTf.setForeground(new java.awt.Color(0, 0, 0));

        huyBtn.setBackground(new java.awt.Color(204, 204, 204));
        huyBtn.setForeground(new java.awt.Color(51, 102, 255));
        huyBtn.setText("Hủy");
        huyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyBtnActionPerformed(evt);
            }
        });

        suaBtn.setBackground(new java.awt.Color(51, 102, 255));
        suaBtn.setForeground(new java.awt.Color(255, 255, 255));
        suaBtn.setText("Sửa");
        suaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 255));
        jLabel13.setText("Thời gian trả dự kiến");

        themTaiLieuBtn.setBackground(new java.awt.Color(51, 102, 255));
        themTaiLieuBtn.setForeground(new java.awt.Color(255, 255, 255));
        themTaiLieuBtn.setText("Thêm");
        themTaiLieuBtn.setPreferredSize(new java.awt.Dimension(60, 50));
        themTaiLieuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTaiLieuBtnActionPerformed(evt);
            }
        });

        xoaTaiLieuBtn.setBackground(new java.awt.Color(51, 102, 255));
        xoaTaiLieuBtn.setForeground(new java.awt.Color(255, 255, 255));
        xoaTaiLieuBtn.setText("Xóa");
        xoaTaiLieuBtn.setPreferredSize(new java.awt.Dimension(49, 50));
        xoaTaiLieuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaTaiLieuBtnActionPerformed(evt);
            }
        });

        soHieuTaiLieuTf.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setText("Số hiệu tài liệu");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 102, 255));
        jLabel16.setText("Số lượng");

        soLuongTf.setForeground(new java.awt.Color(0, 0, 0));

        taiLieuTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        taiLieuTb.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(taiLieuTb);

        thoiGianMuonTf.setForeground(new java.awt.Color(0, 0, 0));
        thoiGianMuonTf.setEnabled(false);

        thoiGianTraDuKienTf.setForeground(new java.awt.Color(0, 0, 0));
        thoiGianTraDuKienTf.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(suaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(huyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(themTaiLieuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xoaTaiLieuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(soHieuTaiLieuTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(soLuongTf, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(soHieuDocGiaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(thoiGianTraDuKienTf)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thoiGianMuonTf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soHieuDocGiaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoiGianMuonTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoiGianTraDuKienTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soHieuTaiLieuTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soLuongTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(themTaiLieuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(xoaTaiLieuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void huyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_huyBtnActionPerformed

    private void suaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBtnActionPerformed
        LocalDateTime thoiGianMuon = muon.getThoiGianMuon();
        LocalDateTime thoiGianTraDuKien = muon.getThoiGianTraDuKien();

        DefaultTableModel model = (DefaultTableModel) taiLieuTb.getModel();
        ArrayList<DongMuon> dsDongMuon = new ArrayList<>();

        int len = model.getRowCount();
        for (int i = 0; i < len; i++) {
            DongMuon dongMuon = new DongMuon();
            Sach sach = new Sach();
            sach.setSoHieu(Integer.valueOf(model.getValueAt(i, 0).toString()));
            dongMuon.setTaiLieu(sach);
            System.out.println(sach.getSoHieu());
            int soLuong = Integer.valueOf(Integer.valueOf(model.getValueAt(i, 1).toString()));
            dongMuon.setSoLuong(soLuong);

            dsDongMuon.add(dongMuon);
        }

        DocGia docGia = new DocGia();
        docGia.setSoHieu(Integer.valueOf(soHieuDocGiaTf.getText()));

        Muon muon = new Muon();

        muon.setDocGia(docGia);
        muon.setDanhSachDongMuon(dsDongMuon);
        muon.setThoiGianMuon(thoiGianMuon);
        muon.setThoiGianTraDuKien(thoiGianTraDuKien);
        muon.sua();
        
        parent.loadDefaultList();
        parent.renderTable();
        
        JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_suaBtnActionPerformed

    private void themTaiLieuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTaiLieuBtnActionPerformed
        String soHieuTaiLieu = soHieuTaiLieuTf.getText();
        String soLuong = soLuongTf.getText();
        DefaultTableModel model = (DefaultTableModel) taiLieuTb.getModel();
        model.addRow(new Object[]{soHieuTaiLieu, soLuong});
        taiLieuTb.setModel(model);
    }//GEN-LAST:event_themTaiLieuBtnActionPerformed

    private void xoaTaiLieuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaTaiLieuBtnActionPerformed
        int index = taiLieuTb.getSelectedRow();
        if (index == -1) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) taiLieuTb.getModel();
        model.removeRow(index);
    }//GEN-LAST:event_xoaTaiLieuBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton huyBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField soHieuDocGiaTf;
    private javax.swing.JTextField soHieuTaiLieuTf;
    private javax.swing.JTextField soLuongTf;
    private javax.swing.JButton suaBtn;
    private javax.swing.JTable taiLieuTb;
    private javax.swing.JButton themTaiLieuBtn;
    private javax.swing.JTextField thoiGianMuonTf;
    private javax.swing.JTextField thoiGianTraDuKienTf;
    private javax.swing.JButton xoaTaiLieuBtn;
    // End of variables declaration//GEN-END:variables
}
