/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ThuThu;

import Entity.ConNguoi;
import Entity.DatTruoc;
import Entity.DocGia;
import Entity.DongDatTruoc;
import Entity.DongMuon;
import Entity.Muon;
import Helper.ThongKe;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tinhlam
 */
public class GiaoDienDatTruoc extends javax.swing.JFrame {

    JFrame parent;
    ArrayList<DatTruoc> ds;

    /**
     * Creates new form GiaoDienDatTruoc
     *
     * @param parent
     */
    public GiaoDienDatTruoc(JFrame parent) {
        this.parent = parent;
        initComponents();
        setup();
    }

    private void setup() {
        final Color BLUE_COLOR = new Color(51, 102, 255, 255);
        final Color WHITE_COLOR = new Color(255, 255, 255, 255);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(BLUE_COLOR);
        headerRenderer.setForeground(WHITE_COLOR);
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        jTable1.setGridColor(BLUE_COLOR);
        jTable1.setForeground(BLUE_COLOR);
        jTable1.setShowGrid(true);
        ds = DatTruoc.layDanhSach();
        renderTable();
    }

    private void renderTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (DatTruoc dt : ds) {
            String sh = String.valueOf(dt.getDocGia().getSoHieu());
            String tgd = dt.getThoiGianDat().format(DateTimeFormatter.ofPattern("dd-MM-yyyy hh:mm:ss"));
            ArrayList<DongDatTruoc> ddt = dt.getDanhSachDongDatTruoc();
            ArrayList<Integer> tl = new ArrayList<>();
            ArrayList<Integer> sl = new ArrayList<>();
            for (DongDatTruoc ddtt : ddt) {
                tl.add(ddtt.getTaiLieu().getSoHieu());
                sl.add(ddtt.getSoLuong());
            }
            model.addRow(new Object[]{sh, tgd, tl, sl});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        topLb = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        centerTopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ngayBatDauDC = new com.toedter.calendar.JDateChooser();
        ngayKetThucDC = new com.toedter.calendar.JDateChooser();
        timTheoNgayBtn = new javax.swing.JButton();
        soHieuDocGiaTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        timTheoSHDocGiaBtn = new javax.swing.JButton();
        datTruocBtn = new javax.swing.JButton();
        choMuonBtn = new javax.swing.JButton();
        centerCenterPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setPreferredSize(new java.awt.Dimension(1000, 800));
        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(51, 102, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        topLb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        topLb.setForeground(new java.awt.Color(255, 255, 255));
        topLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLb.setText("Đặt Trước Tài Liệu");

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(51, 102, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go_back.png"))); // NOI18N
        backBtn.setText("Trở Về");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(176, 176, 176))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        centerPanel.setLayout(new java.awt.BorderLayout());

        centerTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerTopPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Ngày bắt đầu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Ngày kết thúc");

        ngayBatDauDC.setBackground(new java.awt.Color(51, 102, 255));
        ngayBatDauDC.setDateFormatString("dd-MM-yyyy");
        ngayBatDauDC.setMaxSelectableDate(new java.util.Date(253370743299000L));
        ngayBatDauDC.setPreferredSize(new java.awt.Dimension(150, 28));

        ngayKetThucDC.setBackground(new java.awt.Color(51, 102, 255));
        ngayKetThucDC.setDateFormatString("dd-MM-yyyy");
        ngayKetThucDC.setPreferredSize(new java.awt.Dimension(150, 28));

        timTheoNgayBtn.setBackground(new java.awt.Color(51, 102, 255));
        timTheoNgayBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timTheoNgayBtn.setForeground(new java.awt.Color(255, 255, 255));
        timTheoNgayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        timTheoNgayBtn.setText("Tìm");
        timTheoNgayBtn.setBorder(null);
        timTheoNgayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timTheoNgayBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Số hiệu độc giả");

        timTheoSHDocGiaBtn.setBackground(new java.awt.Color(51, 102, 255));
        timTheoSHDocGiaBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timTheoSHDocGiaBtn.setForeground(new java.awt.Color(255, 255, 255));
        timTheoSHDocGiaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        timTheoSHDocGiaBtn.setText("Tìm");
        timTheoSHDocGiaBtn.setBorder(null);
        timTheoSHDocGiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timTheoSHDocGiaBtnActionPerformed(evt);
            }
        });

        datTruocBtn.setBackground(new java.awt.Color(51, 102, 255));
        datTruocBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datTruocBtn.setForeground(new java.awt.Color(255, 255, 255));
        datTruocBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reserve_30px.png"))); // NOI18N
        datTruocBtn.setText("Đặt Trước");
        datTruocBtn.setBorder(null);
        datTruocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datTruocBtnActionPerformed(evt);
            }
        });

        choMuonBtn.setBackground(new java.awt.Color(51, 102, 255));
        choMuonBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        choMuonBtn.setForeground(new java.awt.Color(255, 255, 255));
        choMuonBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/borrow_30px.png"))); // NOI18N
        choMuonBtn.setText("Cho Mượn");
        choMuonBtn.setBorder(null);
        choMuonBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choMuonBtnMouseClicked(evt);
            }
        });
        choMuonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choMuonBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centerTopPanelLayout = new javax.swing.GroupLayout(centerTopPanel);
        centerTopPanel.setLayout(centerTopPanelLayout);
        centerTopPanelLayout.setHorizontalGroup(
            centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngayKetThucDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayBatDauDC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timTheoNgayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soHieuDocGiaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timTheoSHDocGiaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(datTruocBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choMuonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        centerTopPanelLayout.setVerticalGroup(
            centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerTopPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(ngayBatDauDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ngayKetThucDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(centerTopPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(centerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timTheoNgayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(soHieuDocGiaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timTheoSHDocGiaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datTruocBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choMuonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        centerPanel.add(centerTopPanel, java.awt.BorderLayout.PAGE_START);

        centerCenterPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerCenterPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        centerCenterPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số hiệu độc giả", "Thời gian đặt", "Số hiệu tài liệu", "Số lượng tương ứng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        centerCenterPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centerPanel.add(centerCenterPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void timTheoNgayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timTheoNgayBtnActionPerformed
        ArrayList<LocalDate> dates = ThongKe.getMinMaxDate("thoiGianDat", "DatTruoc");
        if (dates == null){
            return;
        }
        LocalDate bd = dates.get(0);
        LocalDate kt = dates.get(1);
        if (ngayBatDauDC.getDate() != null) {
            bd = ngayBatDauDC.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        if (ngayKetThucDC.getDate() != null) {
            kt = ngayKetThucDC.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        ds = DatTruoc.timKiemTheoThoiGian(bd, kt);
        renderTable();
    }//GEN-LAST:event_timTheoNgayBtnActionPerformed

    private void datTruocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datTruocBtnActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bản đặt trước");
            return;
        }
        if (!jTable1.getModel().getValueAt(row, 0).equals("-1")) {
            JOptionPane.showMessageDialog(this, "Đã được đặt trước");
            return;
        }
        ArrayList<ConNguoi> dsDocGia = new DocGia().layDanhSach();
        Integer[] pos = new Integer[dsDocGia.size()];
        for (int i = 0; i < pos.length; i++) {
            pos[i] = dsDocGia.get(i).getSoHieu();
        }
        Integer soHieu = (Integer) JOptionPane.showInputDialog(
                this,
                "Chọn số hiệu độc giả",
                "",
                JOptionPane.PLAIN_MESSAGE,
                null,
                pos,
                pos[0]);
        if (soHieu != null) {
            DatTruoc dt = ds.get(row);
            DocGia dg = new DocGia();
            dg.setSoHieu(soHieu);
            dt.setDocGia(dg);
            dt.datTruoc();
            JOptionPane.showMessageDialog(this, "Đặt trước thành công");
            ds = DatTruoc.layDanhSach();
            renderTable();
        }
    }//GEN-LAST:event_datTruocBtnActionPerformed

    private void timTheoSHDocGiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timTheoSHDocGiaBtnActionPerformed
        if (soHieuDocGiaTf.getText().equals("")) {
            ds = DatTruoc.layDanhSach();
            renderTable();
            return;
        }
        try {
            int soHieu = Integer.valueOf(soHieuDocGiaTf.getText());
            ds = DatTruoc.timKiemTheoSoHieuDocGia(soHieu);
        } catch (NumberFormatException e) {
            ds = new ArrayList<>();
        }
        renderTable();
    }//GEN-LAST:event_timTheoSHDocGiaBtnActionPerformed

    private void choMuonBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choMuonBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_choMuonBtnMouseClicked

    private void choMuonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choMuonBtnActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng dữ liệu");
            return;
        }
        if (jTable1.getModel().getValueAt(row, 0).equals("-1")) {
            JOptionPane.showMessageDialog(this, "Chưa có số hiệu độc giả");
            return;
        }
        DatTruoc dt = ds.get(row);
        Muon muon = new Muon();
        muon.setDocGia(dt.getDocGia());
        muon.setThoiGianMuon(LocalDateTime.now());
        muon.setThoiGianTraDuKien(muon.getThoiGianMuon().plusDays(14));
        ArrayList<DongMuon> dm = new ArrayList<>();
        for (DongDatTruoc ddt : dt.getDanhSachDongDatTruoc()){
            DongMuon dmm = new DongMuon();
            dmm.setTaiLieu(ddt.getTaiLieu());
            dmm.setSoLuong(ddt.getSoLuong());
            dm.add(dmm);
        }
        muon.setDanhSachDongMuon(dm);
        muon.muon(dt);
        JOptionPane.showMessageDialog(this, "Cho mượn thành công");
        ds = DatTruoc.layDanhSach();
        renderTable();
    }//GEN-LAST:event_choMuonBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel centerCenterPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerTopPanel;
    private javax.swing.JButton choMuonBtn;
    private javax.swing.JButton datTruocBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private com.toedter.calendar.JDateChooser ngayBatDauDC;
    private com.toedter.calendar.JDateChooser ngayKetThucDC;
    private javax.swing.JTextField soHieuDocGiaTf;
    private javax.swing.JButton timTheoNgayBtn;
    private javax.swing.JButton timTheoSHDocGiaBtn;
    private javax.swing.JLabel topLb;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
