/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ThuThu;

import UI.GiaoDienDangNhap;
import java.awt.Component;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author tinhlam
 */
public class GiaoDienThuThu extends javax.swing.JFrame {

    GiaoDienDangNhap parent;
    /**
     * Creates new form GiaoDienThuThu
     */
    public GiaoDienThuThu(GiaoDienDangNhap parent) {
        this.parent = parent;
        initComponents();
    }

    public void hienThiThongBao(Component parent, String thongBao){
        JOptionPane.showMessageDialog(parent, thongBao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        changeAccBtn = new javax.swing.JButton();
        topLb = new javax.swing.JLabel();
        botPanel = new javax.swing.JPanel();
        botLb = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        traPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        thongKePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        guiEmailPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        datTruocPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        topPanel.setBackground(new java.awt.Color(51, 102, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        exitBtn.setBackground(new java.awt.Color(255, 0, 0));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Thoát");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        changeAccBtn.setBackground(new java.awt.Color(102, 102, 102));
        changeAccBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeAccBtn.setText("Đổi tài khoản");
        changeAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAccBtnActionPerformed(evt);
            }
        });

        topLb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        topLb.setForeground(new java.awt.Color(255, 255, 255));
        topLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLb.setText("Giao Diện Thủ Thư");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeAccBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(topLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        botPanel.setBackground(new java.awt.Color(51, 102, 255));
        botPanel.setMinimumSize(new java.awt.Dimension(100, 0));
        botPanel.setPreferredSize(new java.awt.Dimension(1000, 30));

        botLb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        botLb.setForeground(new java.awt.Color(255, 255, 255));
        botLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botLb.setText("Copyright © 2023");
        botLb.setPreferredSize(new java.awt.Dimension(1000, 30));

        javax.swing.GroupLayout botPanelLayout = new javax.swing.GroupLayout(botPanel);
        botPanel.setLayout(botPanelLayout);
        botPanelLayout.setHorizontalGroup(
            botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botPanelLayout.createSequentialGroup()
                .addComponent(botLb, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botPanelLayout.setVerticalGroup(
            botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botPanelLayout.createSequentialGroup()
                .addComponent(botLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(botPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setPreferredSize(new java.awt.Dimension(1000, 670));

        traPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        traPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hienThiFormTra(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitHover(evt);
            }
        });
        traPanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(51, 102, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mượn/Trả");
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 50));
        traPanel.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jLabel9.setBackground(new java.awt.Color(51, 102, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return.png"))); // NOI18N
        jLabel9.setOpaque(true);
        traPanel.add(jLabel9, java.awt.BorderLayout.CENTER);

        thongKePanel.setPreferredSize(new java.awt.Dimension(200, 200));
        thongKePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hienThiFormThongKe(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitHover(evt);
            }
        });
        thongKePanel.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(51, 102, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Thống Kê");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 50));
        thongKePanel.add(jLabel7, java.awt.BorderLayout.PAGE_END);

        jLabel13.setBackground(new java.awt.Color(51, 102, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analytics.png"))); // NOI18N
        jLabel13.setOpaque(true);
        thongKePanel.add(jLabel13, java.awt.BorderLayout.CENTER);

        guiEmailPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        guiEmailPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hienThiFormGuiEmail(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitHover(evt);
            }
        });
        guiEmailPanel.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(51, 102, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gửi Email");
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 50));
        guiEmailPanel.add(jLabel5, java.awt.BorderLayout.PAGE_END);

        jLabel10.setBackground(new java.awt.Color(51, 102, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        jLabel10.setOpaque(true);
        guiEmailPanel.add(jLabel10, java.awt.BorderLayout.CENTER);

        datTruocPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        datTruocPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hienThiFormDatTruoc(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitHover(evt);
            }
        });
        datTruocPanel.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(51, 102, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Đặt Trước");
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(200, 50));
        datTruocPanel.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jLabel12.setBackground(new java.awt.Color(51, 102, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reserve.png"))); // NOI18N
        jLabel12.setOpaque(true);
        datTruocPanel.add(jLabel12, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(datTruocPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(traPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(guiEmailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(thongKePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thongKePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(traPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiEmailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datTruocPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_hover

    private void exitHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitHover
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_exitHover

    private void hienThiFormDatTruoc(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hienThiFormDatTruoc
        GiaoDienDatTruoc dt = new GiaoDienDatTruoc(this);
        dt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hienThiFormDatTruoc

    private void hienThiFormGuiEmail(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hienThiFormGuiEmail
        GiaoDienGuiEmail dt = new GiaoDienGuiEmail(this);
        dt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hienThiFormGuiEmail

    private void hienThiFormTra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hienThiFormTra
        GiaoDienMuonTra dt = new GiaoDienMuonTra(this);
        dt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hienThiFormTra

    private void hienThiFormThongKe(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hienThiFormThongKe
        GiaoDienThongKeGiaoDich dt = new GiaoDienThongKeGiaoDich(this);
        dt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hienThiFormThongKe

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void changeAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAccBtnActionPerformed
        parent.setVisible(true);
        parent.resetComponents();
        this.setVisible(false);
    }//GEN-LAST:event_changeAccBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botLb;
    private javax.swing.JPanel botPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton changeAccBtn;
    private javax.swing.JPanel datTruocPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel guiEmailPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel thongKePanel;
    private javax.swing.JLabel topLb;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel traPanel;
    // End of variables declaration//GEN-END:variables
}
